#!/bin/sh
### lolcommits hook (begin) ###
export LANG="en_US.UTF-8"
if which rvm-exec > /dev/null
then
  rvm-exec 2.2@lolcommits lolcommits --capture --stealth --fork --delay=4
else
  lolcommits --capture --stealth --fork --delay=4
fi

###  lolcommits hook (end)  ###
