#!/bin/sh
### lolcommits hook (begin) ###
if ! (cd $(git rev-parse --git-dir) && test -d "./rebase-merge" || test -d "./rebase-apply")
then
  export LANG="en_US.UTF-8"
  if which rvm-exec > /dev/null
  then
	rvm-exec 2.4.1@lolcommits lolcommits --capture --stealth --fork --delay=4
  else
	lolcommits --capture --stealth --fork --delay=4
  fi
fi

###  lolcommits hook (end)  ###
